### ISSUE TITLE
Feature request: Micro-arousal detection

### ISSUE THREAD

**Issue by apavlo89** [raphaelvallat/yasa#34]
It would be amazing if MA detection (different types such as autonomic, cortical, behavioural etc) was added to YASA. It should be relatively easy to code in as well as I imagine small modifications to the spindle detection algorithm should do the trick!

**Comment by raphaelvallat** [comment]
Hi @apavlo89,

I worked on an arousal-detection project a few years ago, and it turned out to be more difficult than initially planned, mostly because arousals can have very different shapes, durations, frequency components, etc. We would therefore need a database of high-quality labels of arousals in a representative sample of the population to create and validate the algorithm. Do you know of any database with high-quality arousal labels?

Thanks,
Raphael
